---
abstract: "some shortcut functions for RDF::Trine's object-oriented interface"
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: RDF::TrineX::Functions
name: RDF-TrineX-Functions
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  IO::Detect: 0.003
  PerlX::Maybe: 0
  RDF::NS: 0
  RDF::Trine: 0.135
  Scalar::Util: 0
  Sub::Exporter: 0
  URI::file: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-TrineX-Functions
  homepage: https://metacpan.org/release/RDF-TrineX-Functions
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-rdf-trinex-functions
version: 0.004
