---
abstract: "some shortcut functions for RDF::Trine's object-oriented interface"
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: '0.61'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Moose::Meta::Class::__ANON__::SERIAL::9 version , CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RDF-TrineX-Functions
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  RDF::TrineX::Functions:
    file: lib/RDF/TrineX/Functions.pm
    version: '0.005'
requires:
  Carp: '0'
  IO::Detect: '0'
  PerlX::Maybe: '0'
  RDF::NS: '0'
  RDF::Trine: '0.135'
  Scalar::Util: '0'
  Sub::Exporter: '0'
  URI::file: '0'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/RDF-TrineX-Functions/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-TrineX-Functions
  homepage: https://metacpan.org/release/RDF-TrineX-Functions
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-rdf-trinex-functions.git
version: '0.005'
